window_color: 'white'

left_key: 'a'
right_key: 'd'

number_of_exercises: 5
number_of_trials_per_block: 5
number_of_blocks: 4

stimuli_color: 'black'
stimuli_x_offset: 3.3
stimuli_y_offset: 3
stimuli_size: 2

prime_time: 0.03
isi_time: 0.045
target_time: 0.09
between_trial_time: 1.5
