window_color: 'white'

left_key: 'a'
right_key: 'd'

number_of_exercises: 12
number_of_trials_per_block: 90
number_of_blocks: 4

stimuli_color: 'black'
stimuli_x_offset: 3.3 #ile od środka w poziomie
stimuli_y_offset: 3 #ile od środka w pionie
stimuli_size: 2
stimuli_thicknes: 0.8 #0-1 im więcej tym chudszy

prime_time: 0.03
isi_time: 0.045
target_time: 0.09
between_trial_time: 1.5

dynamic_fix_duration: 0.750
dynamic_fix_side: 19.0
dynamic_fix_dot_size: 0.2

text_font: 'Arial' #musi mieć polskie znaki
